// DEPLOY TO: app/api/dashboard/templates/from-starter/route.ts

import { NextRequest, NextResponse } from "next/server";
import { getCurrentTenantUser } from "@/lib/tenant-auth";
import { prisma } from "@/lib/db";
import { storage } from "@/lib/storage";
import { getStarter } from "@/lib/templates/starters";
import { wrapHtml, renderHtmlToPdf } from "@/lib/documents/html-to-pdf";
import { captureException } from "@/lib/monitoring";

export async function POST(req: NextRequest) {
  const user = await getCurrentTenantUser();
  if (!user) return NextResponse.json({ error: "unauthorized" }, { status: 401 });

  try {
    const { starterId, folderId } = await req.json();
    const starter = getStarter(starterId);
    if (!starter) return NextResponse.json({ error: "Unknown starter template." }, { status: 400 });

    if (folderId) {
      const folder = await prisma.templateFolder.findFirst({ where: { id: folderId, tenantId: user.tenantId } });
      if (!folder) return NextResponse.json({ error: "That folder doesn't exist." }, { status: 400 });
    }

    const pdfBytes = await renderHtmlToPdf(wrapHtml(starter.bodyHtml));
    const key = `templates/${user.tenantId}/${Date.now()}-${starter.id}.pdf`;
    const stored = await storage.put(key, pdfBytes, "application/pdf");

    const fieldMap = starter.fields.map((f, i) => ({ id: `f_${Date.now()}_${i}`, ...f }));

    const template = await prisma.template.create({
      data: {
        tenantId: user.tenantId,
        name: starter.name,
        pdfStorageKey: stored.key,
        fieldMap: fieldMap as any,
        folderId: folderId ?? null,
        // Deliberately NOT aiDrafted — nothing here was generated by a
        // model, so it doesn't need the AI-review gate. It's still a
        // starting point the sender should customize (the bracketed
        // placeholders in the body text) before sending, same as any
        // template — that's normal editing, not a special review step.
      },
    });

    return NextResponse.json({ template_id: template.id }, { status: 201 });
  } catch (err) {
    await captureException(err, { context: "template_from_starter", tenantId: user.tenantId });
    return NextResponse.json({ error: "Something went wrong creating this template. Please try again." }, { status: 500 });
  }
}
