// DEPLOY TO: app/terms/page.tsx
//
// Reviewed and approved by Upfinity — substantive and specific to this
// product, not boilerplate.

export default function TermsOfServicePage() {
  return (
    <div style={{ maxWidth: 780, margin: "0 auto", padding: "48px 24px 80px" }}>
      <a href="/" className="topbar-brand" style={{ display: "inline-block", marginBottom: 24 }}>Upfinity Sign</a>
      <h1>Terms of Service</h1>
      <p style={{ color: "var(--text-muted)", fontSize: 13 }}>Last updated: August 24, 2026</p>

      <p>
        These Terms of Service ("Terms") govern access to and use of Upfinity Sign (the
        "Service"), provided by Upfinity Inc. ("Upfinity," "we," "us"). By creating a workspace or
        otherwise using the Service, you agree to these Terms on behalf of yourself and, if
        applicable, the organization you represent.
      </p>

      <h2>1. Eligibility and accounts</h2>
      <p>
        You must be at least 18 years old, or the age of majority in your jurisdiction, to create
        a workspace. You're responsible for the accuracy of the information you provide and for
        safeguarding your account credentials and API keys — activity under your account is your
        responsibility, including actions taken by team members you invite.
      </p>

      <h2>2. Description of the Service</h2>
      <p>
        Upfinity Sign lets you upload or generate documents, define fillable/signable fields on
        them, and send them to recipients for signature, approval, or acknowledgment, with an
        audit trail and a Certificate of Completion for each finished document. The Service
        includes optional features — an AI assistant for field placement and document drafting,
        bulk sending, self-serve signing links, payment collection during signing, and API/webhook
        access for integrating with other platforms.
      </p>

      <h2>3. Your content, and the license you grant us</h2>
      <p>
        You retain all ownership rights in the documents, templates, and data you upload or create
        through the Service ("Your Content"). You grant Upfinity a limited license to host,
        process, transmit, and display Your Content solely as necessary to provide the Service to
        you and the recipients you send it to. We do not use Your Content to train AI models, and
        we do not claim any ownership over it.
      </p>
      <p>
        You're responsible for having the right to send, and to request signatures on, whatever
        content you upload — including that you're not using the Service to collect signatures
        fraudulently or without the signer's knowledge.
      </p>

      <h2>4. Acceptable use</h2>
      <p>You agree not to use the Service to:</p>
      <ul>
        <li>Send documents that are fraudulent, deceptive, or intended to trick a recipient into
        signing something they haven't genuinely been given the chance to read;</li>
        <li>Impersonate any person or entity, or misrepresent your affiliation with one;</li>
        <li>Upload content that infringes another party's intellectual property or violates
        applicable law;</li>
        <li>Attempt to circumvent rate limits, tier restrictions, or security controls, or probe,
        scan, or test the vulnerability of the Service without authorization;</li>
        <li>Use the Service to send unsolicited bulk communications outside the ordinary course of
        a legitimate signing workflow;</li>
        <li>Use the Service in violation of applicable export control or economic sanctions laws,
        including sending or receiving documents to or from a person, entity, or jurisdiction
        subject to such restrictions.</li>
      </ul>
      <p>
        We may suspend or terminate accounts that violate this section, with notice where
        practicable.
      </p>

      <h2>5. Signatures and legal validity</h2>
      <p>
        Signatures captured through the Service are recorded with supporting audit data (timestamp,
        IP address, and the verification method used) and embedded into the final signed document
        with a digital signature, together with a separate Certificate of Completion documenting
        the full chain of custody. Whether a given signature is legally enforceable in your
        specific circumstance depends on the law applicable to your transaction and jurisdiction —
        we provide the tools and the record-keeping; we do not provide legal advice about whether
        a particular document or use case is appropriate for electronic signature, and you should
        seek your own legal counsel if you're unsure.
      </p>

      <h2>6. The AI assistant</h2>
      <p>
        Content generated by the AI assistant — whether suggested field placements or a document
        drafted from your description — is a starting point, not a finished, reviewed legal
        document. Any document the assistant drafts from scratch is marked as such and cannot be
        used to send an envelope until a human at your workspace has reviewed and explicitly
        approved it; this is enforced by the Service, not merely a suggestion. You are solely
        responsible for reviewing AI-generated content for accuracy and suitability before relying
        on it. See our <a href="/ai-policy">AI Assistant Notice</a> for more detail.
      </p>

      <h2>7. Fees, billing, and credits</h2>
      <p>
        Paid plans are billed in advance on a recurring basis through our payment processor. If you exceed your plan's monthly allowance for envelopes or AI assistant usage,
        you may purchase additional usage credits or upgrade your plan; we do not silently block
        you without an option to continue. Fees are non-refundable except where required by law or
        expressly stated otherwise. We may change our pricing with at least 30 days' notice before
        it takes effect for existing subscriptions.
      </p>
      <p>
        <strong>Free trial, adding a payment method, and automatic conversion to a paid plan.</strong>{" "}
        New workspaces get a 60-day free trial. Adding a payment method during your trial does{" "}
        <strong>not</strong> charge you anything at that time — we only save the card for later use,
        the same way a hotel or car rental hold works, not a charge. Starting 45 days into your
        trial, a payment method is required to continue sending new documents (your existing
        documents and account data remain fully accessible regardless). <strong>If a payment
        method is on file when your 60-day trial ends, we will automatically begin charging that
        payment method on a recurring monthly basis at our then-current price for the plan your
        workspace converts to</strong> (currently our Starter plan — see Settings for the exact
        current price before you add a card), continuing every month thereafter until you cancel.
        You can cancel or downgrade at any time before your trial ends to avoid this charge, with
        no penalty, from Settings → Plan. If no payment method is on file when your trial ends,
        your workspace is paused (not deleted) until you add one — nothing is charged in that case
        either. We will email you before your trial ends as a reminder either way.
      </p>
      <p>
        If your workspace enables payment collection from your own recipients during signing, that
        is a separate transaction between you and your recipient, processed via your own connected
        payment account — Upfinity is not a party to it and does not take custody of those funds.
      </p>

      <h2>8. Third-party integrations</h2>
      <p>
        The Service can be integrated with other platforms (for example, Upfinity Talent) via API
        and webhooks. If you enable such an integration, you're responsible for the credentials
        and configuration on both sides, and for ensuring the other platform's own terms and
        privacy practices are acceptable to you and, where relevant, to the recipients whose data
        flows through the integration.
      </p>

      <h2>9. Intellectual property</h2>
      <p>
        The Service itself — its software, design, and branding — is owned by Upfinity Inc. and
        protected by applicable intellectual property laws. These Terms do not grant you any
        rights to our trademarks, logos, or brand assets beyond what's needed to use the Service
        as intended.
      </p>

      <h2>10. Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, EXPRESS
        OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
        NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR
        THAT ANY DOCUMENT'S ELECTRONIC SIGNATURE WILL BE ENFORCEABLE IN EVERY JURISDICTION OR FOR
        EVERY USE CASE.
      </p>

      <h2>11. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, UPFINITY WILL NOT BE LIABLE FOR ANY INDIRECT,
        INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE,
        DATA, OR GOODWILL, ARISING FROM YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY FOR ANY CLAIM
        ARISING OUT OF THESE TERMS WILL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE MONTHS
        PRECEDING THE CLAIM. NOTHING IN THESE TERMS LIMITS LIABILITY THAT CANNOT LAWFULLY BE
        LIMITED, INCLUDING FOR GROSS NEGLIGENCE, WILLFUL MISCONDUCT, OR FRAUD.
      </p>

      <h2>12. Indemnification</h2>
      <p>
        You agree to indemnify and hold Upfinity harmless from any claim arising from your use of
        the Service in violation of these Terms, Your Content, or your violation of any law or the
        rights of a third party.
      </p>

      <h2>13. Termination</h2>
      <p>
        You may stop using the Service and request deletion of your workspace at any time from
        Settings → Danger zone. We may suspend or terminate your access for violation of these
        Terms, non-payment, or as required by law, with notice where practicable. Sections that by
        their nature should survive termination (ownership, disclaimers, limitation of liability,
        indemnification, dispute resolution) will survive.
      </p>

      <h2>14. Dispute resolution and governing law</h2>
      <p>
        If a dispute arises, the parties will follow these steps in order, each a required
        precondition to the next:
      </p>
      <ol>
        <li><strong>Informal resolution.</strong> Contact us at privacy@upfinity.ca and we'll work
        in good faith to resolve the dispute directly — most issues are resolved at this stage
        without needing to go further.</li>
        <li><strong>Arbitration.</strong> If informal resolution doesn't resolve the dispute within
        30 days, either party may refer it to binding arbitration administered by the ADR Institute
        of Canada under its applicable rules, seated in Toronto, Ontario, before a single
        arbitrator, conducted in English.</li>
        <li><strong>Court.</strong> If arbitration concludes without resolving the dispute (for
        example, the arbitrator is unable to reach a decision, or either party is otherwise
        entitled to have the matter heard by a court under the arbitration rules that applied),
        either party may bring the matter before the courts located in Toronto, Ontario, which
        will have exclusive jurisdiction over it from that point.
        </li>
      </ol>
      <p>
        This sequence does not limit either party's right to seek urgent injunctive relief from a
        court at any stage where immediate harm would otherwise result. These Terms are governed by
        the laws of the Province of Ontario and the federal laws of Canada applicable therein,
        without regard to conflict-of-law principles, except where applicable local law requires
        otherwise for consumers in your jurisdiction.
      </p>

      <h2>15. Miscellaneous</h2>
      <p>
        <strong>Entire agreement.</strong> These Terms, together with our Privacy Policy, AI
        Assistant Notice, and (where applicable) Data Processing Agreement, constitute the entire
        agreement between you and Upfinity regarding the Service, superseding any prior agreements
        on the subject.
      </p>
      <p>
        <strong>Severability.</strong> If any provision of these Terms is found unenforceable, the
        remaining provisions will remain in full effect, and the unenforceable provision will be
        interpreted to reflect its original intent as closely as permitted by law.
      </p>
      <p>
        <strong>No waiver.</strong> Our failure to enforce any provision of these Terms is not a
        waiver of our right to do so later.
      </p>
      <p>
        <strong>Assignment.</strong> You may not assign or transfer these Terms without our
        written consent. We may assign these Terms in connection with a merger, acquisition, or
        sale of assets, with notice to you where required.
      </p>
      <p>
        <strong>Force majeure.</strong> Neither party is liable for delay or failure to perform
        caused by circumstances beyond its reasonable control, including natural disaster, war,
        internet or infrastructure failure, or government action.
      </p>
      <p>
        <strong>Notices.</strong> We may provide notice to you via the email address on your
        account or a prominent notice within the Service. You may provide notice to us at
        privacy@upfinity.ca.
      </p>

      <h2>16. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. We'll post the updated version here with a
        new "Last updated" date, and for material changes, provide at least 30 days' notice (such
        as an email to workspace owners) before the change takes effect.
      </p>

      <h2>17. Contact us</h2>
      <p>
        Upfinity Inc.<br />
        140 Carlton Street, Toronto, ON M5A 3W7, Canada<br />
        <strong>privacy@upfinity.ca</strong>
      </p>

      <p style={{ marginTop: 40 }}>
        <a href="/privacy">Privacy Policy</a> · <a href="/dpa">Data Processing Agreement</a> ·{" "}
        <a href="/ai-policy">AI Assistant Notice</a> · <a href="/">Back to Upfinity Sign</a>
      </p>
    </div>
  );
}
