// DEPLOY TO: lib/templates/starters.ts
//
// A curated set of common document starters — NDA, offer letter, service
// agreement, etc. — so creating a template doesn't have to start from a
// blank upload or an AI prompt every single time. Reuses the exact same
// HTML → PDF pipeline the AI assistant's generate_document action uses
// (lib/documents/html-to-pdf.ts), just with pre-written content instead
// of AI-generated content — these are NOT AI-drafted (no aiDrafted flag,
// no mandatory review gate), since nothing here was generated by a model;
// they're static, hand-written starting points a sender still customizes
// and reviews like any other template before sending.

import type { FieldType } from "../signing/field-types";

export interface StarterField {
  page: number;
  type: FieldType;
  role: string;
  x: number;
  y: number;
  width: number;
  height: number;
  required: boolean;
}

export interface TemplateStarter {
  id: string;
  name: string;
  description: string;
  bodyHtml: string;
  fields: StarterField[];
}

const SIG_BLOCK = (roleLabel: string, y: number): StarterField[] => [
  { page: 1, type: "full_name", role: roleLabel, x: 72, y, width: 220, height: 24, required: true },
  { page: 1, type: "signature", role: roleLabel, x: 72, y: y + 30, width: 220, height: 40, required: true },
  { page: 1, type: "date", role: roleLabel, x: 320, y: y + 30, width: 120, height: 24, required: true },
];

export const TEMPLATE_STARTERS: TemplateStarter[] = [
  {
    id: "mutual_nda",
    name: "Mutual NDA",
    description: "Standard mutual non-disclosure agreement between two parties.",
    bodyHtml: `
      <h1>Mutual Non-Disclosure Agreement</h1>
      <p>This Mutual Non-Disclosure Agreement ("Agreement") is entered into between the two
      parties identified below (each a "Party," together the "Parties") for the purpose of
      preventing unauthorized disclosure of Confidential Information as defined below.</p>
      <h2>1. Definition of Confidential Information</h2>
      <p>"Confidential Information" means any non-public information disclosed by either Party,
      whether orally or in writing, that is designated as confidential or that reasonably should
      be understood to be confidential given the nature of the information and the circumstances
      of disclosure.</p>
      <h2>2. Obligations</h2>
      <p>Each Party agrees to (a) hold the other Party's Confidential Information in strict
      confidence, (b) not disclose it to any third party without prior written consent, and (c)
      use it solely for the purpose of evaluating or pursuing the business relationship between
      the Parties.</p>
      <h2>3. Term</h2>
      <p>This Agreement remains in effect for two (2) years from the date of last signature,
      unless terminated earlier by mutual written consent.</p>
      <h2>4. Governing Law</h2>
      <p>This Agreement is governed by the laws of the jurisdiction agreed upon by the Parties
      separately.</p>
      <div style="margin-top:60px;"><p><strong>Party A</strong></p></div>
      <div style="margin-top:100px;"><p><strong>Party B</strong></p></div>
    `,
    fields: [...SIG_BLOCK("Party A", 560), ...SIG_BLOCK("Party B", 680)],
  },
  {
    id: "offer_letter",
    name: "Offer Letter",
    description: "Standard employment offer letter with role, compensation, and start date.",
    bodyHtml: `
      <h1>Offer of Employment</h1>
      <p>Dear [Candidate Name],</p>
      <p>We are pleased to offer you the position of <strong>[Job Title]</strong> at
      <strong>[Company Name]</strong>, reporting to <strong>[Manager Name]</strong>. This letter
      outlines the key terms of your offer.</p>
      <h2>Position &amp; Start Date</h2>
      <p>Your anticipated start date is <strong>[Start Date]</strong>. This is a
      [full-time/part-time] position.</p>
      <h2>Compensation</h2>
      <p>Your starting annual salary will be <strong>[Salary]</strong>, paid on the company's
      standard payroll schedule, along with eligibility for the benefits described in our
      employee handbook.</p>
      <h2>At-Will Employment</h2>
      <p>Employment with the Company is at-will, meaning either you or the Company may terminate
      the employment relationship at any time, with or without cause or notice.</p>
      <p>Please sign below to accept this offer.</p>
      <div style="margin-top:60px;"><p><strong>Candidate</strong></p></div>
      <div style="margin-top:100px;"><p><strong>Company Representative</strong></p></div>
    `,
    fields: [...SIG_BLOCK("Candidate", 560), ...SIG_BLOCK("Company Representative", 680)],
  },
  {
    id: "service_agreement",
    name: "Service Agreement",
    description: "General services agreement between a service provider and a client.",
    bodyHtml: `
      <h1>Service Agreement</h1>
      <p>This Service Agreement ("Agreement") is entered into between the Service Provider and
      the Client identified below.</p>
      <h2>1. Services</h2>
      <p>Service Provider agrees to perform the following services for Client:
      <strong>[Description of Services]</strong>.</p>
      <h2>2. Fees &amp; Payment</h2>
      <p>Client agrees to pay Service Provider <strong>[Fee Amount]</strong>, payable
      <strong>[Payment Terms]</strong>.</p>
      <h2>3. Term &amp; Termination</h2>
      <p>This Agreement begins on the date of last signature and continues until the Services are
      completed, unless terminated earlier by either party with written notice.</p>
      <h2>4. Independent Contractor</h2>
      <p>Service Provider is an independent contractor, not an employee, agent, or partner of
      Client.</p>
      <h2>5. Limitation of Liability</h2>
      <p>Neither party's liability under this Agreement will exceed the total fees paid under
      it.</p>
      <div style="margin-top:60px;"><p><strong>Service Provider</strong></p></div>
      <div style="margin-top:100px;"><p><strong>Client</strong></p></div>
    `,
    fields: [...SIG_BLOCK("Service Provider", 560), ...SIG_BLOCK("Client", 680)],
  },
  {
    id: "liability_waiver",
    name: "Liability Waiver",
    description: "General release and waiver of liability for an activity or event.",
    bodyHtml: `
      <h1>Release and Waiver of Liability</h1>
      <p>In consideration of being permitted to participate in
      <strong>[Activity/Event Name]</strong>, I, the undersigned, agree to the following:</p>
      <h2>1. Assumption of Risk</h2>
      <p>I understand that participation in this activity involves inherent risks, and I
      voluntarily assume all such risks.</p>
      <h2>2. Release</h2>
      <p>I hereby release, waive, and discharge <strong>[Organizer/Company Name]</strong>, its
      officers, employees, and agents from any and all liability for any injury, loss, or damage
      arising from my participation, except in cases of gross negligence or willful misconduct.</p>
      <h2>3. Acknowledgment</h2>
      <p>I have read this waiver, understand its terms, and sign it voluntarily.</p>
      <div style="margin-top:60px;"><p><strong>Participant</strong></p></div>
    `,
    fields: SIG_BLOCK("Participant", 500),
  },
];

export function getStarter(id: string): TemplateStarter | undefined {
  return TEMPLATE_STARTERS.find((s) => s.id === id);
}
